version: '3.8'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.0
    container_name: echo-es
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - xpack.security.enabled=false  # makes curl simpler
    ports:
      - "9200:9200"
    networks:
      - echo-net

networks:
  echo-net:
    driver: bridge
