name: EchoSearch Crawl

on:
  workflow_dispatch:

jobs:
  crawl:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # IMPORTANT:
      # Only runs the crawler. No saving JSON. No committing output.
      - name: Run Scrapy crawler
        env:
          ES_HOST: "https://407f6567cff94b42a621cb81c626064c.europe-west2.gcp.elastic-cloud.com:443"
        run: |
          scrapy crawl echo_spider
